// AUTOGENERATED FILE
// This file was generated from amorfs.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface AmorfsActionDict<T> extends BaseActionDict<T> {
  Document?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode) => T;
  TopLevel?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Concept_withValue?: (this: NonterminalNode, arg0: IterationNode, arg1: NonterminalNode, arg2: IterationNode, arg3: IterationNode) => T;
  Concept_reference?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Concept_expressionOnly?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  Concept?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ValueBlock?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode, arg4: TerminalNode) => T;
  ValueContent?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode, arg4: IterationNode) => T;
  ValueItem?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Association?: (this: NonterminalNode, arg0: IterationNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  Expressions?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode, arg4: IterationNode) => T;
  Expression?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  ExpressionValue?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Metadata?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode, arg4: TerminalNode) => T;
  MetadataContent?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  MetadataItem?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  languageCode?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  confidence?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  importance?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  temporal?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  temporalRange_startEnd?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: IterationNode) => T;
  temporalRange_endOnly?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  temporalRange?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  customAttribute?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  attrValue?: (this: NonterminalNode, arg0: IterationNode) => T;
  conceptRef?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  iri?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  iriContent?: (this: NonterminalNode, arg0: IterationNode) => T;
  quotedString?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  stringContent?: (this: NonterminalNode, arg0: IterationNode) => T;
  escapeSequence?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  number?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode, arg3: IterationNode, arg4: IterationNode, arg5: NonterminalNode) => T;
  exponent?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  datetime?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: IterationNode) => T;
  date?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode, arg3: NonterminalNode, arg4: TerminalNode, arg5: NonterminalNode, arg6: NonterminalNode, arg7: TerminalNode, arg8: NonterminalNode, arg9: NonterminalNode) => T;
  time?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: NonterminalNode, arg5: TerminalNode, arg6: NonterminalNode, arg7: NonterminalNode, arg8: IterationNode, arg9: IterationNode) => T;
  timezone?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  timezoneOffset?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: NonterminalNode, arg3: TerminalNode, arg4: NonterminalNode, arg5: NonterminalNode) => T;
  text?: (this: NonterminalNode, arg0: IterationNode) => T;
  textChar?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  structuralDelimiter?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  delimiter?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  identifier?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode, arg1: IterationNode) => T;
  Comment?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  associationOp?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  itemSep?: (this: NonterminalNode, arg0: TerminalNode) => T;
  decimalNumber?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode) => T;
  ws?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  space?: (this: NonterminalNode, arg0: TerminalNode) => T;
  newline?: (this: NonterminalNode, arg0: TerminalNode) => T;
}

export interface AmorfsSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: AmorfsActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: AmorfsActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: AmorfsActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: AmorfsActionDict<T>): this;
}

export interface AmorfsGrammar extends Grammar {
  createSemantics(): AmorfsSemantics;
  extendSemantics(superSemantics: AmorfsSemantics): AmorfsSemantics;
}

declare const grammar: AmorfsGrammar;
export default grammar;

